#
# Makefile for ADI Authenticate IC
#
obj-$(CONFIG_BATTERY_AUTH_DS28E30) += sec-auth-ds28e30.o
sec-auth-ds28e30-$(CONFIG_BATTERY_AUTH_DS28E30) += sec_auth_ds28e30.o 1wire_protocol.o bignum.o deep_cover_coproc_SW.o ds28e30.o ecc_generate_key.o ecdsa_generic_api.o ecdsa_high.o sha256_stone.o ucl_rng.o ucl_sha256.o ucl_sys.o sec_auth_qos_devfreq_setting.o